COPY (
	SELECT
		s.nct_id,
		s.nlm_download_date_description,
		s.study_first_submitted_date,
		s.results_first_submitted_date,
		s.disposition_first_submitted_date,
		s.last_update_submitted_date,
		s.study_first_submitted_qc_date,
		s.study_first_posted_date,
		s.study_first_posted_date_type,
		s.results_first_submitted_qc_date,
		s.results_first_posted_date,
		s.results_first_posted_date_type,
		s.disposition_first_submitted_qc_date,
		s.disposition_first_posted_date,
		s.disposition_first_posted_date_type,
		s.last_update_submitted_qc_date,
		s.last_update_posted_date,
		s.last_update_posted_date_type,
		s.start_date_type,
		s.start_date,
		s.verification_date,
		s.completion_date_type,
		s.completion_date,
		s.primary_completion_date_type,
		s.primary_completion_date,
		s.target_duration,
		s.study_type,
		s.acronym,
		s.baseline_population,
		s.brief_title,
		s.official_title,
		s.overall_status,
		s.last_known_status,
		s.phase,
		s.enrollment,
		s.enrollment_type,
		s.source,
		s.limitations_and_caveats,
		s.number_of_arms,
		s.number_of_groups,
		s.biospec_retention,
		s.biospec_description,
		s.why_stopped,
		s.has_expanded_access,
		s.expanded_access_type_individual,
		s.expanded_access_type_intermediate,
		s.expanded_access_type_treatment,
		s.has_dmc,
		s.is_fda_regulated_drug,
		s.is_fda_regulated_device,
		s.is_unapproved_device,
		s.is_ppsd,
		s.is_us_export,
		s.ipd_time_frame,
		s.ipd_access_criteria,
		s.ipd_url,
		s.plan_to_share_ipd,
		s.plan_to_share_ipd_description,
		s.created_at,
		s.updated_at,
		i.id AS intervention_id,
		i.name AS drug_name
	FROM ctgov.studies s
		JOIN ctgov.interventions i ON i.nct_id = s.nct_id
	WHERE s.study_type ILIKE 'INTERVENTIONAL' AND i.intervention_type ILIKE 'DRUG'
	)
TO STDOUT WITH (FORMAT CSV,HEADER,DELIMITER E'\t')
	;
